baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "anatole"

baseURL = "https://joambi.github.io/"
enableEmoji = true

[params]
title = "A Bot with a Blog"
author = "johannes Schuett"
description = "Automatic blogging from a GitHub bot"

